### PR TITLE
Using dirty-checking for displaying current user

### PR DESCRIPTION
**Pull request by azevedo-252**

### CODE REVIEW

**Comment by naps62** [comment]
Angular n00b here. I don't understand what's being done here
I see a lot of code removed, but I don't understand where is this dirty checking being added

Can you explain?

**Comment by azevedo-252** [comment]
Well it's simple, I'm just letting angular do what he does best - dirty checking.
Without getting into much details, in angular, data bindings only get updated whenever the $digest cycle is triggered. That usually happens when you use some angular directive or service, or some 3rd party angular module or when you explicitly tell it so (by calling $apply or $digest programmatically).

In this feature's case, the current user gets updated when a promise from angular-data gets resolved. angular-data uses $q internally, which works exclusively with the $digest cycle and whenever a promise resolves it triggers the cycle.
So, i just needed to make the function that displays the currentUser *watchable*, as it would be updated when the promise which gets the current user resolved. Previously I wasn't really aware of this, and implemented this behavior with a PubSub approach which is really unnecessary, hence the code removal.

**Comment by gabrielpoca** [comment]
Finally I was able to show you something new about Angular :) :+1:

**Comment by azevedo-252** [comment]
@gabrielpoca is that a "go on merge it" ?

**Comment by gabrielpoca** [comment]
yes

**Pull request merged**
